# Nixpacks configuration for Railway
[variables]
NODE_ENV = "production"
ENABLE_HEALTH_CHECK = "true"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
